### ISSUE TITLE
Links clickable outside texts.

### ISSUE THREAD

**Issue by CoderS2020** [codeisscience/journal-policy-tracker-frontend#136]
**Describe the bug**
The links in the contact section of manifesto page (i.e.. links for twitter, email and github) are clickable outside as well.

**To Reproduce**

1. Go to Manifesto page
2. Hover/ Click around right side of twitter/email/github links below contact section.
3. See error

**Screenshots**

https://user-images.githubusercontent.com/71634100/162799086-9fdc78ba-a978-4a37-a63d-107dd4e37089.mp4

**Desktop (please complete the following information):**

- OS: [Windows 10
- Browser:  Chrome

**Comment by CoderS2020** [comment]
Hello , greetings. If this issue seems valid may I work on it?

**Comment by padmajabhol** [comment]
This has been fixed, pull the latest commits.

**Comment by CoderS2020** [comment]
Hello @padmajabhol , I pulled the latest commits, but still the bug remains the same. I also checked the other issues.
Extremely sorry if I am doing some mistake and troubling you.
